app2.config(['$translateProvider', function ($translateProvider) {
  $translateProvider.translations('en', {
		Login : '  Login',
				Profile: 'Profile',
				Logintoyouracount : 'Login to your account',
                Amlapp  :  'AML APP',
                Notmemberyet : 'NOT A MEMBER YET?',
                Signup   :  'Sign up',
                Forgotpassword :  '  Forgot password?',
                Username  :  '  Username',
                Password  : '  Password',
                Addnewagent : 'Add New Agent',
                Name : '  Name',
                EmailID : '  Email Address',
                Mobile : '  Mobile No',
                Save : 'Save',
                Cancel : 'Cancel',
                Addcompanydetails : '  Add Company Details ',
                Companyname : '  Company Name',
                Addresscompany :'  Address of company:',
                Fiscalid : '  Fiscal Id',
                CompanyDocument : 'Company Document',
                CompanyLicense : 'Company License',
                Companyauthorizedby : '  Company authorised by',
                DateofAutorized : '  Date Of Authorization',
                FiscalBudget : '  Fiscal Budget',
                Addnewcustomer : 'Add New Customer',
                Addressofresidence : '  Address of residence',
                Adddocument : 'Add Document',
                Documenttitle : '  Document Title',
                Upload_documentimage : 'Upload Document Image',
                Add_New_Owner : 'Add New Owner',
                My_Companies : 'My Companies',
                Actforperson : 'Act for Person',
                Contract :'Contract',
				ContractList	:'Contract List',
				CustomerList	:'Customer List',
				CompanyList	:    'Company List',
                Firstname : '  First Name',
                Lastname : '  Last Name',
                Address : '  Address',
                ProgressiveofServiceContract : '  Progressive of Service Contract',
                ScopeofContract : '  Scope of Contract',
                NatureofContract : '  Nature of Contract',
                EconomicValueifDeterminable : '  Economic Value if Determinable',
                EnterNameofPersonorCompanies : '  Enter Name of Person or Companies',
                Contractformownersfootertext : '  List of Beneficial owner for companies with their Number of ID Documents and validity',
                Number_validity_id  : '  Number and Validity of ID Documents',
                Risk_defined :'  Risk defined',
                Entername : '  Enter Name',
                Contractformownersfootertext2 : 'If type of customers is a company will be stored also the name of the person that act for the companies ',
                Editagent : 'Edit Agent',
                EditCompanyDetails : 'Edit Company Details',
                Editcustomer : 'Edit Customer',
                Dob : 'Date of Birth',
                EditOwners : '  Edit Owners',
                Forgot : '  Forgot Password',
                MyAgents : '  My Agents',
                PersonalInformation :  'Personal Information',
                Surname : '  Surname',
                Country : '  Country',
                Profession : '  Profession',
                Tel : '  Tel',
                Fax : '  Fax',
                SaveExit : 'Save & Exit',
                SaveNext : 'Save & Next',
                OtherDetails : 'Other Details',
                PleaseSelectnyoneid : 'Please select type of Identification Document ',
                AuthoritythatreleasedIdentityDocument : '  Authority that released Identity Document',
                ReleaseDateofIdentityDocument : '  Release Date of Identity Document',
                ValidityDateofIdentityDocument : '  Validity Date of Identity Document',
                Declarationif : 'Declaration   if',
                Pep : 'PEP ',
                PEPNOT : 'PEP-NOT',
                Annualincome : '  Annual income',
                YourAddress : '  Your Address',
                ResidenceCountry  : 'Residence Country',
                DomicileCountry  : 'Domicile Country',
                AddressofDomicileResidence  : '  Address of Domicile Residence',
                MainNationality : '  Main Nationality',
                FiscalNumber : '  Fiscal Number',
                OwnerDetails : 'Owner Details',
                Roleofuserwithcompany : '  Role of user with company',
                PARTTOBEFILLEDVIABOAWOA : 'PART TO BE FILLED VIA BOA / WOA',
                Economicvalueofservice : '  Economic value of service',
                Natureofservice : '  Nature of service',
                Scopeofservice : '  Scope of service',
                DocumentsList : 'Documents List',
                MyCustomers : 'My Customers',
                Profile : 'Profile',
                ChangePassword : 'Change Password',
                CurrentPassword : '  Current Password',
                NewPassword : '  New Password',
                ConfirmPassword : '  Confirm Password',
                Submit : 'Submit',
                BeneficialownerofCompanies : 'Beneficial owner of Companies',
                EditAgentProfile : 'Edit Agent Profile',
                CloseAccount : 'Close Account',
                EditInformation :  'Edit Information',
                UploadDocuments : 'Upload Documents',
                EditKycForm : 'Edit Kyc Form',
                RiskAnalysis : 'Risk Analysis',
                ContractForm : 'Contract Form',
                RiskAnalysisPersonalInformation : 'Risk Analysis-Personal Information',
                PersonalExposedpolitically : 'Personal Exposed politically',
                HighRisk : 'High Risk',
                LowRisk : 'Low Risk',
                CriminalPreceedings : 'Criminal Preceedings',
                PresenceInList : 'Presence In List',
                Other : '  Other',
                Mainactivitywithhighuseofcash : 'Main activity with high use of cash',
                Mainactivitywitheuropianfinancincfunds : 'Main activity with europian financinc funds',
                RiskAnalysisMainActivity : 'Risk Analysis-Main Activity',
                Itseemsthathasenoughskillstomainactivity : 'It seems that has enough skills to main activity ',
                Mainactivitywithhighvolumeoffinancialmovements : 'Main activity with high volume of financial movements',
                Mainactivitywithpucsectorfundsinancing : 'Main activity with puc sector funds financing',
                NotCollaborativeatall : 'Not Collaborative at all',
                ToomuchCollaborative : 'Too much Collaborative',
                Collaborative : 'Collaborative',
                RiskAnalysisClientBehavior : 'Risk Analysis-Client Behavior ',
                RiskAnalysisFrequency : 'Risk Analysis-Frequency',
                Consistency : 'Consistency',
                Highfrequencybusiness : 'High frequency business',
                Relationcontinuityinresonableconsistencyofeconomicprofileofclients : 'Relation continuity in resonable consistency of economic profile of clients',
                Frequencyanddurationofbusinessconsistentwitheconomicprofileofclient : 'Frequency and duration of business consistent with economic profile of client',
                Dimensionofbusinessinconsistentwitheconomicandpatrimonialprofileofclient  : 'Dimension of business inconsistent with economic and patrimonial profile of client',
                TransparentOwnership : 'Transparent Ownership',
                Corporatepurposenoncleanandcompreensive : 'Corporate purpose non clean and compreensive',
                ComplexPartecipartorylink : 'Complex Partecipartory link',
                Conectionwithsubjectinriskcountry : 'Conection with subject in risk country',



                Enterresidenceaddress : 'Enter Residence Address',
                Enterdomiaddress : 'Enter Domicile Address',
                Identification:'Identification',

                placeofidentification:'Place Of Identification',
                dateofidentification:'Date Of Identification',

              placeofidentification_validitymsg:"Please Enter Place Of Identification",
              dateofidentification_validitymsg:"Please Select Date Of Identification",
              weatherdomiciledifferentfromresedence:"Whether residence different from domicile",



              //27 feb 2017
              customercontactinfo:"Customer Contact Info",
              surname:"Surname",
              placeofbirth:"Select place of birth",
              placeofbirthvalidte:"please select place of birth",
              personalinformation:"Personal information",
              ifpep:"If PEP",
              domestic:"Domestic",
              foreign:"Foreign",

							//AX
							AddnewContract:"add a new contract/sevice",
							ContractDate:"Contract Date",
							ContractEOV:"End of Validity of Contract",
							SearchCustomer:"Search Customer"

 })
 $translateProvider.preferredLanguage('en');
 }]);
