app2.config(['$translateProvider', function ($translateProvider) {
  $translateProvider.translations('it', {
		Login : 'Accesso',
			Profile: 'Il mio Profilo',
							Logintoyouracount : 'Accedi al tuo account',
							Amlapp  :  'AML APP',
							Notmemberyet : 'NON SEI ANCORA UN MEMBRO?',
							Signup   :  'Registrazione',
							Forgotpassword :  'Ha dimenticato la password?',
							Username  :  'Nome utente',
							Password  : "  parola d'ordine",
							Addnewagent : 'Aggiungi nuovo agente',
							Name : 'Nome',
							EmailID : 'Indirizzo email',
							Mobile : 'cellulare No',
							Save : 'Salvare',
							Cancel : 'Annulla',
							Addcompanydetails : 'Inserisci una nuova Società ',
							Companyname : 'Nome della società',
							Addresscompany :'Indirizzo della società:',
							Fiscalid : 'Fiscal Id',
							PIVA : 'Partita IVA o COE',
							CompanyDocument : 'Document Company',
							CompanyLicense : 'Licenza società',
							Companyauthorizedby : 'Società autorizzata da',
							DateofAutorized : 'Data di autorizzazione',
							FiscalBudget : 'Fatturato Annuo',
							Addnewcustomer : 'Aggiungi nuovo cliente',
							Addressofresidence : 'Indirizzo di residenza',
							Adddocument : 'Aggiungi documento',
							Documenttitle : 'Titolo del documento',
							Upload_documentimage : 'Carica documento Immagine',
							Add_New_Owner : 'Aggiungi Titolare Effettivo',
							My_Companies : 'Le mie aziende',
							ContractList	:'Contratti',
							CustomerList	:'Persone Fiscihe',
							CompanyList	:    'Persone Giuridiche',
							Actforperson : 'Agisce per se Stesso',
							Contract :'Contratto',
							Firstname : 'Nome',
							Lastname : 'Cognome',
							Address : 'Indirizzo',
							ProgressiveofServiceContract : 'CPU',
							ScopeofContract : 'Scopo del contratto',
							NatureofContract : 'Natura del contratto',
							EconomicValueifDeterminable : 'Valore economico se determinabile',
							EnterNameofPersonorCompanies : 'Immettere il nome della persona o della società',
							Contractformownersfootertext : " Elenco dei beneficiario per le società con il loro numero di documenti d'identità e validità",
							Number_validity_id  : "  Numero e validità dei documenti d'identità",
							Risk_defined :'rischio definito',
							Entername : 'Inserisci il nome',
							Contractformownersfootertext2 : 'Se il tipo di cliente è una società verrà memorizzato anche il nome della persona che agisce per le aziende ',
							Editagent : 'Modifica agente',
							EditCompanyDetails : 'Modifica Società',
							Editcustomer : 'Modifica dei clienti',
							Dob : 'Data di nascita',
							EditOwners : 'Modifica proprietari',
							Owners: "Titolari Effettivi",
							OwnersList: "Elenco dei Titolari Effettivi",
							Forgot : 'Ha dimenticato la password',
							MyAgents : 'I miei agenti',
							PersonalInformation :  'Informazione personale',
							Surname : 'Cognome',
							Country : 'Nazione',
							Profession : 'Professione',
							Tel : 'Telefono',
							Fax : 'Fax',
							SaveExit : 'Salvare & Uscita',
							SaveNext : 'Salvare & Il prossimo',
							OtherDetails : 'Altri dettagli',
							PleaseSelectnyoneid : 'Selezionare qualsiasi ID',
							AuthoritythatreleasedIdentityDocument : 'Autorità che ha rilasciato documento di identità',
							ReleaseDateofIdentityDocument : 'Data di rilascio del documento di identità',
							ValidityDateofIdentityDocument : 'Validità data del documento di identità',
							Declarationif : 'Dichiarazione se',
							Pep : 'PEP ',
							PEPNOT : 'PEP-NOT',
							Annualincome : 'Reddito annuo',
							YourAddress : 'Il tuo indirizzo',
							ResidenceCountry  : 'Paese di residenza',
							DomicileCountry  : 'domicilio Paese',
							AddressofDomicileResidence  : 'Indirizzo di domicilio Residence',
							MainNationality : 'Nazionalità principale',
							FiscalNumber : 'codice fiscale',
							OwnerDetails : 'proprietario Dettagli',
							Roleofuserwithcompany : "  Ruolo nella Società",
							PARTTOBEFILLEDVIABOAWOA : 'PARTE DA COMPILARE VIA BOA / WOA',
							Economicvalueofservice : 'Valore economico del servizio',
							Natureofservice : 'Natura del servizio',
							Scopeofservice : 'Portata del servizio',
							DocumentsList : 'Elenco documenti',
							MyCustomers : 'I miei clienti',
							MyContract : 'I miei contratti',
							Profile : 'Profilo',
							ChangePassword : 'Cambia la password',
							CurrentPassword : 'Password attuale',
							NewPassword : 'nuova password',
							ConfirmPassword : 'conferma password',
							Submit : 'invio',
							BeneficialownerofCompanies : 'Titolari Effettivi ',
							EditAgentProfile : 'Modifica Profilo agente',
							CloseAccount : "Chiudere l'account",
							EditInformation :  'Profilo',
							UploadDocuments : 'Carica Documenti',
							EditKycForm : 'Adeguata Verifica',
							RiskAnalysis : 'Analisi del rischio',
							ContractForm : 'Stampa Form',
							RiskAnalysisPersonalInformation : 'Analisi-Personal Rischio Informazioni',
							PersonalExposedpolitically : 'Personal esposto politicamente',
							HighRisk : 'Alto rischio',
							LowRisk : 'A basso rischio',
							CriminalPreceedings : 'Preceedings penale',
							PresenceInList : 'Presenza In List',
							Other : 'Altro',
							Mainactivitywithhighuseofcash : 'Principali settori di attività ad alto uso del contante',
							Mainactivitywitheuropianfinancincfunds : 'Principali settori di attività con i fondi financinc europian',
							RiskAnalysisMainActivity : 'Analisi-Main rischio Activity',
							Itseemsthathasenoughskillstomainactivity : "Sembra che non ha competenze sufficienti per l'attività principale",
							Mainactivitywithhighvolumeoffinancialmovements : 'Principali settori di attività con elevato volume di movimenti finanziari',
							Mainactivitywithpucsectorfundsinancing : 'Principali settori di attività con un finanziamento fondi del settore puc',
							NotCollaborativeatall : 'Non collaborativo a tutti',
							ToomuchCollaborative : 'Troppo Collaborative',
							Collaborative : 'Collaborative',
							RiskAnalysisClientBehavior : 'Behavior Analysis-client rischio ',
							RiskAnalysisFrequency : 'Analisi dei rischi-Frequency',
							Consistency : 'Consistenza',
							Highfrequencybusiness : 'imprese ad alta frequenza',
							Relationcontinuityinresonableconsistencyofeconomicprofileofclients : 'la continuità relazione in coerenza ragionevole di profilo economico di clienti',
							Frequencyanddurationofbusinessconsistentwitheconomicprofileofclient : 'Frequenza e la durata di attività coerenti con il profilo economico del cliente',
							Dimensionofbusinessinconsistentwitheconomicandpatrimonialprofileofclient  : 'Dimensione di attività in contrasto con il profilo economico e patrimoniale del cliente',
							TransparentOwnership : 'Proprietà trasparente',
							Corporatepurposenoncleanandcompreensive : 'Oggetto sociale non pulito e compreensive',
							ComplexPartecipartorylink : 'Complesso collegamento Partecipartory',
							Conectionwithsubjectinriskcountry : 'Entrare in contatto con soggetti a rischio paese',
							Enterresidenceaddress : 'Enter Residence Address',
							Enterdomiaddress : 'Enter Domicile Address',
							Identification:'Identification',
							placeofidentification:'Place Of Identification',
							dateofidentification:'Date Of Identification',
  						 placeofidentification_validitymsg:"Please Enter Place Of Identification",
						 weatherdomiciledifferentfromresedence:"Whether residence different from domicile",

						//27 feb 2017
						customercontactinfo:" Modifica Cliente",
						surname:" Surname",
						placeofbirth:" Select place of birth",
						placeofbirthvalidte: " please select place of birth",
						personalinformation:" Personal information",
						ifpep:" Se PEP",
						domestic:" Domestico",
						foreign:" Straniero",
						//AX
						AddnewContract:" Aggiungi un nuovo contratto",
						ContractDate:" Data del Contratto",
						ContractEOV:" Scadenza del Contratto",
						SearchCustomerByEmail:" Cerca Cliente ",
						SearchCompanyByEmail:" Cerca Società inserendo la mail del dichiarante",
						SearchDelegatorByEmail:" Cerca Delegante inserendo la mail inserendo la mail del dichiarante",
						addNewCompany:" Aggiungi una nuova Società",
						actForHimself: " Agisce per se stesso",
						actForCompany: " Agisce per una società",
						actForOtherPerson: " Agisce per un altra persona",
						addNewOtherPerson:" aggiungi Delegante",
						kindofDelegation:" Aggiungi tipo di procura/delga ",
						Upload_contract: " Carica documento contratto/conferimento ",
						NewCustomer:"Nuovo Cliente",
						EditContract:"Modifica Contratto"
  });

  $translateProvider.preferredLanguage('it');
 }]);
